### ISSUE TITLE
Feature request: replay recording of game

### ISSUE THREAD

**Issue by AndrewPaxie** [thjc/lwf#3]
I was wondering if a "replay game" feature would be worth it. Then we could all sit back and celebrate the best moves. 

In simple view it's just the board placements that can be stepped through. 
In advanced view, each players draw is visible. This allows spectators second guess the moves and criticise,

One possible implementation could be as a slider on a timeline, allowing jumps to non-linear points in time.

As a bonus, allow the game to be saved as a video.

**Comment by thjc** [comment]
Basics have been implemented, hands remain hidden and no video
